language: objective-c
osx_image: xcode7.2
before_script:
- pod lib lint
language: objective-c
xcode_workspace: Example/YXTUnsatisfiableConstraintsDetector.xcworkspace 
xcode_scheme: YXTUnsatisfiableConstraintsDetector-Example 
xcode_sdk: iphonesimulator
# Command: xctool test -scheme YXTUnsatisfiableConstraintsDetector-Example -workspace Example/YXTUnsatisfiableConstraintsDetector.xcworkspace -sdk iphonesimulator
